from __future__ import annotations

import hashlib
import json
import os
import shutil
from pathlib import Path
from typing import Any

import numpy as np
import torch


class FixtureWriter:
    """Atomic writer for a self-describing fixture.

    ``name`` may contain a directory (for example ``raw/view_0_rgb_u8``).
    The metadata file list is generated by the writer, so a validator can
    reject stale or untracked files.
    """

    def __init__(self, output_dir: Path | str, fixture_id: str, overwrite: bool = False):
        self.output_dir = Path(output_dir)
        self.fixture_id = fixture_id
        self.fixture_dir = self.output_dir / fixture_id
        if self.fixture_dir.exists() and not overwrite:
            raise FileExistsError(f"fixture directory already exists: {self.fixture_dir}")
        self._work_dir = self.output_dir / f"{fixture_id}.tmp.{os.getpid()}"
        if self._work_dir.exists():
            shutil.rmtree(self._work_dir)
        self._work_dir.mkdir(parents=True, exist_ok=False)
        self._files: dict[str, dict[str, Any]] = {}
        self._metadata: dict[str, Any] = {"fixture_version": 2, "fixture_id": fixture_id}
        self._finalized = False

    @staticmethod
    def _sha(data: bytes) -> str:
        return hashlib.sha256(data).hexdigest()

    def _write(self, relative: str, data: bytes, *, dtype: str, shape: list[int], kind: str) -> None:
        path = self._work_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        self._files[relative] = {
            "path": relative, "kind": kind, "dtype": dtype, "shape": shape,
            "byte_length": len(data), "sha256": self._sha(data),
        }

    def write_metadata(self, metadata: dict) -> None:
        self._metadata.update(metadata)
        self._metadata["fixture_id"] = self.fixture_id

    def write_instruction(self, instruction: str) -> None:
        data = instruction.encode("utf-8")
        self._write("instruction.txt", data, dtype="utf8", shape=[len(data)], kind="text")

    def write_tensor(
        self,
        name: str,
        tensor: torch.Tensor | np.ndarray,
        dtype_suffix: str = "f32",
        binary_filename: str | None = None,
    ) -> None:
        cpu = tensor.detach().cpu().contiguous() if isinstance(tensor, torch.Tensor) else torch.from_numpy(np.ascontiguousarray(tensor))
        base = name.removesuffix("_f32").removesuffix("_bf16")
        npy_path = f"{name}.npy"
        npy_file = self._work_dir / npy_path
        npy_file.parent.mkdir(parents=True, exist_ok=True)
        if cpu.dtype == torch.bfloat16:
            # NumPy cannot represent BF16 portably. Store exact uint16 bits in .npy.
            np_array = cpu.view(torch.uint16).numpy()
            npy_dtype = "bfloat16_bits_u16"
        else:
            np_array = cpu.numpy()
            npy_dtype = str(np_array.dtype)
        with npy_file.open("wb") as stream:
            np.save(stream, np_array, allow_pickle=False)
        npy_data = npy_file.read_bytes()
        self._files[npy_path] = {"path": npy_path, "kind": "npy", "dtype": npy_dtype,
                                 "shape": list(cpu.shape), "byte_length": len(npy_data), "sha256": self._sha(npy_data)}

        if binary_filename:
            binary_path = str(Path(name).parent / binary_filename) if Path(name).parent != Path(".") else binary_filename
        elif dtype_suffix == "f32":
            binary_path = f"{base}_f32le.bin"
        elif dtype_suffix == "bf16":
            binary_path = f"{base}_bf16le.bin"
        elif dtype_suffix in {"i64", "i64le"}:
            binary_path = f"{base}_i64le.bin"
        else:
            binary_path = f"{name}.bin"
        if dtype_suffix == "f32":
            array = cpu.float().numpy().astype("<f4", copy=False)
            dtype = "float32"
        elif dtype_suffix == "bf16":
            if cpu.dtype != torch.bfloat16:
                raise ValueError(f"expected bfloat16 tensor, got {cpu.dtype}")
            array = cpu.view(torch.uint16).numpy().astype("<u2", copy=False)
            dtype = "bfloat16"
        elif dtype_suffix in {"i64", "i64le"}:
            array = cpu.long().numpy().astype("<i8", copy=False)
            dtype = "int64"
        elif cpu.dtype == torch.bool:
            array, dtype = cpu.to(torch.uint8).numpy(), "uint8"
        else:
            array, dtype = cpu.numpy(), str(cpu.numpy().dtype)
        self._write(binary_path, array.tobytes(), dtype=dtype, shape=list(cpu.shape), kind="raw")

    def write_image(self, name: str, image: np.ndarray) -> None:
        array = np.ascontiguousarray(image, dtype=np.uint8)
        npy_path = f"{name}.npy"
        npy_file = self._work_dir / npy_path
        npy_file.parent.mkdir(parents=True, exist_ok=True)
        with npy_file.open("wb") as stream:
            np.save(stream, array, allow_pickle=False)
        npy_data = npy_file.read_bytes()
        self._files[npy_path] = {"path": npy_path, "kind": "npy", "dtype": "uint8", "shape": list(array.shape),
                                 "byte_length": len(npy_data), "sha256": self._sha(npy_data)}
        self._write(f"{name}.bin", array.tobytes(), dtype="uint8", shape=list(array.shape), kind="raw")

    def finalize(self) -> Path:
        if self._finalized:
            return self.fixture_dir
        self._metadata["files"] = [self._files[key] for key in sorted(self._files)]
        metadata_data = json.dumps(self._metadata, indent=2, ensure_ascii=False, allow_nan=False).encode("utf-8") + b"\n"
        (self._work_dir / "metadata.json").write_bytes(metadata_data)
        if self.fixture_dir.exists():
            old = self.output_dir / f"{self.fixture_id}.old.{os.getpid()}"
            if old.exists():
                shutil.rmtree(old)
            self.fixture_dir.rename(old)
            self._work_dir.rename(self.fixture_dir)
            shutil.rmtree(old)
        else:
            self._work_dir.rename(self.fixture_dir)
        self._finalized = True
        return self.fixture_dir

    def abort(self) -> None:
        if self._work_dir.exists():
            shutil.rmtree(self._work_dir)
